sudo: required

services:
  - docker

env:
  global:
    - IMAGE_TAG=$TRAVIS_COMMIT-$TRAVIS_BUILD_NUMBER
    - PATH=$PATH:/tmp/
    - AWLESS_VERSION=0.1.9
    - AWLESS_PACKAGE=awless-linux-386.tar.gz
    - STACK_NAME=archersaurus
    - STACK_TEMPLATE_FILE=templates/archersaurus.yml
    - STACK_CONFIG_FILE=templates/archersaurus.config.yml 

before_install:
  - wget --quiet https://github.com/wallix/awless/releases/download/v$AWLESS_VERSION/$AWLESS_PACKAGE
  - tar xv -C /tmp/ -f $AWLESS_PACKAGE

script:
  - make image
  - make awless_deploy 
  - make awless_watch

